### ISSUE TITLE
英字や式を正常に変換してくれない

### ISSUE THREAD

**Issue by kusanome** [matuku/DarkestDungeonWayaku#2]
どうにも英字と{colour_start|notable}{colour_end}のような式を正常に変換（この場合はそのまま記載）してくれません。
英字はすっぽぬけ式はその後の文章が変換されなくなっています

**Comment by kusanome** [comment]
それと感嘆符や疑問符や半角スペースなども

**Comment by matuku** [comment]
ご報告ありがとうございます。

**Comment by matuku** [comment]
遅くなりましたが修正しました。
おそらく解消したんじゃないでしょうか
